CREATE TABLE RESTAURANTS (
  ID VARCHAR (255),
  NAME VARCHAR(255),
  PRIMARY KEY (ID)
);

CREATE TABLE RESTAURANT_MENU_ITEMS (
  RESTAURANT_ID VARCHAR (255),
  ID VARCHAR(255),
  NAME VARCHAR(255),
  AMOUNT DECIMAL (12,2),
  PRIMARY KEY (ID)
);