stripe:
  publishKey: pk_test_Shp16QZvyaRP7nBlDGxowgM9
  secretKey: sk_test_CLv4CREGjWZOUqhqIIUIB45Q
  ftgoToken: rk_test_NH3GOhYuzHMp690PYL473NAs
eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: account-service
  cloud:
    stream:
      bindings:
        orderCreateIn:
          destination: orderCreateEventOut
          group: orderAccount
        orderCreateOut:
          destination: orderCreateEventIn
          group: orderAccount
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
server:
  port: 8093

